### ISSUE TITLE
Komplettering

### ISSUE THREAD

**Issue by axeberg** [chas-academy/dragons-06-imdb-clone#130]
Hej @chas-academy/dragons,

Här kommer det ni behöver komplettera för att kunna få godkänt på denna uppgift.

- Delvis gjord denoteras med **~**
- Det som är gjort denoteras med en ifylld checkbox 
- Det ni behöver komplettera denoteras med tom checkbox

 - [~]  En webbplats skriven med PHP för backend, JS, HTML och CSS för front-end samt en databas i MySQL
  - [X]  Ska använda sig av PHP-ramverket Laravel
- [X]  En MySQL databas med tabeller och data som är skapade via Laravel migrations
- [ ]  Webbplatsen ska ha tre olika typer av delar:
  - [~]  **En publik del** ska kunna besökas utan inloggning för vanliga besökare
  - [~]  **En inloggad del som då kräver registrering där man som användare:**
    - [x]  Ska kunna recensera filmer
    - [x]  Se, skapa och ändra i listor med filmer som man vill se (se IMDb:s watchlist)
  - [~]  **En skyddad del**, där endast en administratör kan logga in för att göra följande:
    - [x]  Hantera recensioner och kommentarer (godkänna, ta bort)
    - [~]  CRUD-operationer för filmer
    - [~]  CRUD-operationer för användare
- [~]  Design är också en del av uppgiften och skall skapas av teamet. Det är tillåtet att nyttja CSS-ramverk såsom Bootstrap eller dylikt. Kolla gärna in följande sida för inspiration (**OBS**: Inspiration, inte som i kopiera):

## Övriga krav på arbetet

- [X]  I ert team ska ni arbeta agilt och dela upp arbetet i iterationer. Ni har 6 veckor totalt så längden på era iterationer kan variera. Vi föreslår att ni använder er av en-veckas "sprintar/cykler/iterationer"
  - [X]  Strukturera ert arbete i små leverabler som ni klarar känner att ni i ert team är uppnåbara
  - [X]  Illustrera ert planerade, pågående och avslutade arbete med Kanban (digitalt eller fysiskt)
  - [~]  Det ska göras minst en deploy varje vecka. Tänk igen på att dela upp er leverabel i så små delar som möjligt - *Release often, deploy a lot*
- [~]  Hela teamet ska använda sig av [GitHub Flow](https://guides.github.com/introduction/flow/) när ni versionshanterar
- [ ]  Ni ska i teamet komma överens om kodingstandard och se till att samtliga i teamet följer den

### Sedan fattas följande från kravspecifikationen:

- [x] Personas och User Stories
- [x] Sitemap
- [x] Wireframes

**Comment by martinfjant** [comment]
Wireframes, personas och userstories finns men dock inte på github. Skall vi lägga dem som PDF:er i en mapp och köra upp det, eller i vilket format vill du ha det?

**Comment by axeberg** [comment]
Ge mig en länk till det som finns bara @martinfjant

**Comment by MichaelTariao** [comment]
https://drive.google.com/drive/folders/15Nmoe96mW8Rkj8YptmzOzdUHrL5QgLW9

**Comment by axeberg** [comment]
Dessa är tabellerna jag tänker att ni behöver:
---
- [ ] movies
- [ ] people
- [x] genres
- [x] genre_movie (**genres > movies**)
- [x] watchlist
- [x] reviews

**Comment by MichaelTariao** [comment]
https://drive.google.com/drive/folders/15Nmoe96mW8Rkj8YptmzOzdUHrL5QgLW9?usp=sharing

**Comment by axeberg** [comment]
Come on @chas-academy/dragons - so close.
